---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAZdiJpCN84OkssLr0T2KKfmWobUhQhPiCItdeTLaOohRMuEUsTnhtVDPbaDoZbz+isJZzI+QpKTfpGRyXuc4DRBTq0mWWW/1ooWh0u9oKK4I46829ckUqbq5klc/8Fn47goFqv58jpn1CK9MME1FiZnz9TyPbTrqfg5I9qqxz5aew+5wYvj3jxA1wYAdkgtQojnFvpUsWv/XRUdg/bJiNTfVAa37CCOzlKWv0NyV0bi2aKolHnyFToEp1a+F2pIhQdGq6+054njILQKIPbProK7l10ZTJRnV8vOs/l+ffJ4tZdG5PiJfzvIylCbyQaFRk1RpgDec9PeNNsQsWasvtJaZOnaNSFmSv2sP12cr/jaL1L5n90qFmVoPlFSlWX56IK5qS2vuMy5W/7Hp+kFm3K92GqJdHmFWg8b5T3qhh06zUPmLzV6qZHQsqJ9p7oxTNnqv6T7s1rUxIG9r2AxWbR0tHLXv9631u+cA3JeZxhuYK0eY0h5hSVfI/JpqhffOOGAwHh9ToNTXnvp8Se+Mui0zJCsnkFwgfm37pPvJpprKocpuuc9Yeuabr5Zadmdv5cLkKz/JDnGZ2GantlPHzd3z1tNOs+7OWHcCIzknBP8VNWn03414VuiKNyMZUFtHs/pwDpO9KVQpSClp0rwN8m4tJW8YMSTNw9G9//OggnjtPogX+bGSA8+0Xv7I/mTTQbWzDk4VNswZvhMiU41IOFkXYukbSJ0RmdoRU=
    admin-user: AgBVHWsCaokbKgJrw1qJo81teiwPuAz8WKnKan3T4oxyXB0YVAH0ueeLmiqoVWhCB3Ny4H1e+1mNnzWqgEdpyqjiagfkpi8r/VaJCDSUfjLYyA9SuZBmz0ZJREm1BqlFq8msdRE8bx83n3WZ0j6QT+deWe30EN442hMR+7tOrSF8Nnec/jmJxcs+gLGvGL1l2hk7x40KyQdyZWQ4BCZs/AtBcDwz5oYM54DqFGBA1MV2emviqeJ0q8lmFGFb0n3M74EdXJ0iYqE6J7V+N/Os/dCUmTbIrsyXyMvCmcflKeaitCHAFqSri9pGTnSXgApG1IROjA/YbfHh1gLsGnKPQiccyz7Ny5Deu+Ya9sAzbsvB7T5uLvCZSSUNBTASy99/BdO9H/9QFewpbU+7Lzv1gK2jWijMvyCs6bWToUZ5CL8ZzdUxxJvgYt29TGk9vl547/N/hFkyHqUerKHIN8DC/+PD5W9pRp/f65YZhmjKI/iU+E43AL0HhSS/QTnKVK6lfvAOy9W4H8Hc5T5YkjUa1GMa1AjaRW/O9/pM4uCkxd/36Wbhq50azxHn46AKwI5JQBBbbRfDLGBjY56l4RjHhnTjmKH0TGDG3A1ipHi00gZjyEVDMCLrnGaNdDB83pFDkYOE0k6m/JStAelN6pE4lL8uElyuJXxs1bxBrNWTCqhvUdqPnlbYEEtF06IaJsFmREI5dWidXA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
