---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCUduUY6jsERZXRq8iqYn0tvA3LiO7PGrpgqSVFZB19W9M072iRGFn0t/Vih+SLSUAYPzZ+ZDTu6EpfvQhfs7yRgtKWpIv5k3ETNE3SxTCREmlEtBAsZ5HFcZiaaYgv0HlIUMXCTnM+Q3FFQdpfBOarVUmq8+5ArKS2Y/jYRLMboPjfUjFG6v76GuU0m/W0ssK+faZkoesm0/zlZ3Nd22cy0N5rGvmgM+6btWOxn8I6xtoW9NegUml5WqXsSCwT6OCfg8+ax2uNKPfL1U4uFd3XojfzcXryxzO+lNSqj8zfPeJ163fzIJYW2rhqOOZtj+0H2LisltiQPwBAjB3EsFtGx4mltcLBtCjSPPMtViJTnIExkTJySkwgdCvNgfkPME6AqSaEbXPveyCd3JNAh8ZtRf6S6QdLcYMFcBzi+wMLslAFNT2gywGJlLMgnBtpY5uRPaJyKFXuci26WKVBjl8MlYAabsK67YMknLqrTsuOlTlDO20RW5eBpWN+lXTXr3/Xf3qa2UyKAevyspFtfZKl2mQznxNGpz6tHpYfhX6JwSntj5UIu8Nu44aiTMNZOCIg93k9x9vRihCzZ15UIGLcfkF6qvHd1gobEGb+26RPxO0kedRUTjXmq7tm09xT+cJ3yXML94ChIzmMn1GcsVRwN1zkCrczTnsEdlqXhR1WRgU3otdi2ANtSWSwOFCUKDuEgxeaSKL/ZfY3EpuRLR9rQKDYUylDP5QII8c=
    admin-user: AgA8FbLIEs/5el3zsycMSsNSxBGY6dDjLOvLkEpJoEF5YUnIifdw0FbsQ/VP+KF27DRadAzgV6+5jRBoxfrTzE3XPK1BFRseV099M2a/RT4RcUcAdxRDl7v/bcR4tqfubY42R0EV6tfl7TTZw/UeFxLfxQBvVkXHKxpf44z6fygehLJFiGlSs7jmwXWB9C4bqnidpcrxXib8HXVopOFBsmZIcdPF0S2PQ47iQE40OfAeCN2s3aiMSdem2ofN7FHVXGi8R7UmLbHEPf0/ICg4MIrwuq6/Di1wd61/2Eo2XQFZ22IMKr/9uQF3ma1d5YWR67yPfWSH4/uN5cumj/tmHuM1pKWbYu1OPQTxEeRVzzxYo2o2Y2cxIPy9qQyF48dkpjH/IibR4gDrsGGQXBzf9v/CM41DBhX9UB0Y/yvrfPFBeSrLr4COobbqLljjGiulkLVprCesDQt+R+xG286o5LFrLRQ6nnu+LjFLHeCjfR7zeBbiHmAN4mQILVO7BofXHRLX/qiGSfaR3BMxwtrnHnKO5M2Cd+yu5s102E+3Y98SFCH0Br9jiHCS+GOooU+8U0b0TkQQDDs9EnpUHWYG0t02V+ri4y4W9AtLMmbFFXQ/713yKAmLny5HiZtW58LM47nKCx1rb4Qr6kt5TKZfknpvmuXrZmihPItbQL8UA+KGr6AliJ4UZRfhtSD8X4dyixnvoiHUlA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
