prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelector: {}

grafana:
  adminPassword: "admin"
  service:
    type: ClusterIP