---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: website-db-credentials
  namespace: portfolio
spec:
  encryptedData:
    DB_PASSWORD: AgCUbcqM1Jttqns0td4B4GAcE1rnPvVwoFPIVFZ9dIrhQOaMrlyd+h+Ul33e/bTYCdYitiWJcOIjYkvUo4tEe++3Mioo9fvprOVAqXyf2WEbFl3DY1zrUFx+etXJAPHVXh2ccsjE8sDMcivFHWOXPun1852jnDoip39JIpDJ9RMp/BNBbE4mKY1M4p0ACgd5yZI8XvOxUMfHWp3jS3iPU4tBuAcLuPwADNLO9Felte8G/B5GBm8XsP1vaWZWBFyaiABABjIUYZD5P1+h6jv0Tb1k2cdpkF08oXmbqcu75gdPlUZynCaXh29/S06CGtkzUTB69N0kjXouQSPYsU+bXDpG14KMVzhRhfI/DlKlAuUB7GgqfSDVT+QS4qkJ5MkYgL1ffHp65Tigy5rfVudXW/GVlC0Gi6v6SCnVV3WjjISYu+kJwznfEIa0AZ5RRIw+DEcwSKWUxMSXwoZ+KpU0UkR37Wgq27DUrsu/YHk3juGEr9LUFGfVYj8eabFxdHLD+FdwZoBaNpMT/WRLE7G7gvo2d72zMrBLy8fYXxt3+5TqUQjAxQtCtHOSpDaFtQvO30fGIuDbb0mHwHSSkgj3X6pDhkVMnyfe0eGW4Zd/gO3DMarJpdefePtGAhay8eocdgMo1EfaXnPF56Lixs0VTLGXfvmB8qWasSpOLN6Lbvo5nKrBDQ+nmTKIUkdBlcaWAmffUG0IHB1opKYXgFXAdvB/13lEORBDfg==
    DB_USERNAME: AgDX/QX1Hgi4vlkpMjMsq4pu+8hlN7twMXFYFvw5gCv/USTT4qk+7zVfGGMgMA/hDkYGDnRQhRI1ls9h1r3xJDweeYgyurYTiZKMhkMVWPSMZBdpgiGAs+NVwys9s1sYzPO3SW6GuEhQecPDJ4DOQZLHyrsh3oQo1XXsCzwGbdFAGcOo8KAEbD4Js9qS5mxGI+PXLvkUTi/qXG++sL1WrpqpefisgNvZ0QtHTa3WHJ97VGgjKrf5fe7K5Sl8g5zNUDe3PXZEADwL1gPYVlHIr0A/fFqsIKLLGFLGfCJAFBLe8koqznfG51cVVt6cr+NPw0h7WCzwE9GKjovuM1+8e8NRF8VL3011lW7Njhw9E2e8xXW5vKbhCh0r1Sy1gIjytjFb9oq8NfKybbxB9onenbjSVCNe3SBsa74NLMQ/fqM9BDe2GOcybMx3PiwKLDWCtAa1TuIuLv4rt6pMqw+mwxcZve1D8y+UyZX3tFO02HFENr408t6K2DMILSV6QiM8vVScmb2fkhSpNDk14JwEJ5W7LW8F1t7UaG9UFlPPeNWFMPrvpgrpfEDiFWCWDC8rF+cVScZ0m+zHFRymu/ZVs9bUfwHDTegPvsQmywgsr+kNiUwYwDUnLPS2y+p1QAZfVuTENBowV2YOMygwj6TAX9qT9sOVOf8/Crf127XZ2qC+wYrpLOympek5AZSSK7oKqaSrI1oqB/4fijD+Z6uaxbk=
  template:
    metadata:
      creationTimestamp: null
      name: website-db-credentials
      namespace: portfolio
