---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: website-db-credentials
  namespace: portfolio
spec:
  encryptedData:
    DB_PASSWORD: AgCGNxyTQZTeoQ/Pi7GyISodHoR/vQ8gByYXVMxf4ePRnSo6zzE9r6pnQmSesR7XEN1u/9W6jHh9RNmR+vnEH3091Ux9q4DnaBUAq8XwRLcajQaaIU5esO/vR5NDKrNEwt7TDON74mAvWirKrxw6YRfbZGf1tutbM3VN5CmN7f00sd/ekEc1eyXzdYsJHtiQ6pmv+8LHtq7NhxzvEOEMePgQW0DXacUDkvuAVs+00U4wucYAEHWbYoVF9O99PrTVp1TYJl1pwxIt0ArgXUU/zNJunprZktLklevFsgp+apt2d8KnodFO2k25bSGXN7/M98trFf9cJdrqfCsAgSrr+v8I6xl8NDEMdX+Fz8Yf4lv8Eeo/EV7hstPpGOuKvY4GqYuADI4boax10yTBs2G6yecwoQ/CPF8BGOnGvsWtqClCRLWyP0cC9VHHXDp4qa5GkI+SZzFaxlH9JFVw8wd1CXNHPH1ctq1Qwza5Bxlhc7OW5nwVRluX83P3da5dedVToH+Z0kzoLKo7srh+2yJheLeDsEhSBRWj2KWt1HCvU9A5kkgQhuZGpCDcVug/QOr/UzfUWYamlMCJj/nOsdgrb8TpXb+NBzHVn9w8Gr3FQuMvdOMcYioxns2HKUhCMxOwvz9WqTTLto6nv2B++vIgiuruOFdp+sJXEj0pr7scF216fFjXLlI61S8Fy8j++i9NMUctPcl52AsBhYawwoV5tyPb9oC+ifEJVA==
    DB_USERNAME: AgCPlg5PNRdZLRzqKywPlPhdFLwzM2WfJixX3D6xOZFBhCwiUUp+9uQeB4gZ0pDdtrIFhPxG7aLbIKj4k6oq7Ye9i65piIyCLtByrRJ5mjyDuigzLJ99M6/mI+j0rjCx200BqrnyfHu9uLnJNxsLsQ3GybIwLOJ4jZLDyMUS1EQbx+flA2Uh+BUgnzjh8bECc7/kFLMRm6HEPWmC0CTSFapjuSF32p9Tbll1cpjQ5dkGvdFDnLAEURfimk12Zn2jHXDtJArjwX8glQbyg2YSsi2t1uFUllgy8xZDatDQNZtGOhNDEYSopuyHzlYXzmqWw2gDdEnmRi3kVe17vbK3IFe2R9pBhVPiWUozQcmxPibr6rI+ZoS7D9Fpcp9RF30g7yZ/DzNxfmCfrBlmctPxSIMCim/cqkCvtOKiB3F9BK8BFClAt7OQnFvRXLex4XZPcza7y4wXl9q5AO4jgB7iCVcptLndxfWVoBqZETMeaJTyVYQwvy6mThTmr59pxI0on94EBo0f/YjuEXwZcZYvuNhJ/vBrshoXoN2TSNoKZYwKsylrZk/cRJsQ3JD58V8jkCjKWiM6rlZHxL2DDyzmSSZgn8VmLCoiCysn1d0b4vnIInnv5l71nXnPynuw2X77Amwe7maDptXUzOEdfyKSKvIRUe50iPTfXOVa0NCsMzRaDIO+wTTQA5ihTz88XLxqmMH28B2rmTFPRQxDAqW6Kls=
  template:
    metadata:
      creationTimestamp: null
      name: website-db-credentials
      namespace: portfolio
