---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: website-db-credentials
  namespace: portfolio
spec:
  encryptedData:
    DB_PASSWORD: AgBsK4kOSHKCJ3ioWXD3gwirEiai7u8Cb73sm4wMUtLAjHiCPHp/x6Gcti3cu8EmNy35SWByxUb+0726PiC4c1WOKhfWted6NZQ0f3i1zMo7dRlsV8aHvBX5vcoCuLJ9FNww50KZYdkYaKw2u0c9So5PSjB1LuWYomkWt/rGmRCpYcv/kiYg/TcV/2v0s/0xPpG2n5Grs/4O0ID3lkS5wObfbg3KbTjTSbLBgjB9kAkSe7henv4VQMik0WbC2nPYmoxXJ+KjDOUEc9ripuDD+YrsfqbOUXe16RXry8zbnwxMrnllIkaHSyf2SL9a5bMCQd/7rj2AloBLcpqNou9SDHAUxGrMLtFwP8aVoCQroSyMMEoBreN9gyAgTzWUXTHsat2kDYY4/dG9L/UX+9ye5cQ5lZwkb+nzfO6EuwIGyJdVEhgjP6EQqB98toLOLzEcpR4W03PtqGYdwm21EJPhVQtFwDRw+MrnYryXIpXQrZ6AY8s16R5MMsOeP+UNW0GT18EFyULH61m/mE4HsE6xmsJsK7MQrO7yoqmSGUVlwTVWI1IatAXOtIthjcPAuAg4awEjtWOOj4lM1ShwP5IFZR4ZmvUSgqoI51AmCHj0VZoYUlsFsvrcTcDGcrSqEtdycyv1vPx2vhUZghBXya5e4TZl5/UZ2XYyYnBMUeQBT8MbdiBWeMTAc6PFE1Us4AVBDoMedo27nOZdF2uCwnNUGfsPogVVccUyKQ==
    DB_USERNAME: AgCyFa73P3G8M4ul6p8Nce+g1CxIRmbkqfdAv94EJaYJYZd2VBhLyDUgg0/zj8nNU33XK5DskHftiK5JU+iXKO6E9CMgNYnBv/GkXcCQliif2QBTXycqCzIxMUqqProq/OA5vU14mxL/M0xIy7ELl5SKIVoq4pzajwSJQBPSaa/OsIQwTIbFAawG8vg8r6qE1lbgHz6M2veotfMq2oTtjgbSmGgon8iKVQqgjBse6OTBi3qzSV0AkI211d/kdGEuPBJ4XouvNxp6lfTA346YswnX3IR9huMbuIAAvfliUGeK9d0LrnWWCMQU/4BDZ/Q6JYOrHQUvlGCf+kiv2rx00OCNVCsHCAsbYH7+3WJPl7vpUIcu6vAN6ssRbgwsRGvbPxcwRvQzrg2tN2ZS+lUWWYddD3xoBHtlMImvtLBNw3Ulspg5UiQGraChVxN8g3rixV07M5p6zPjtuhzxZi9bsOqG++RSxZy9TY58+mOPMstkO36qG/QHYY+ULIJI4ujRt9/nD/Zpp4EvAiR7NeDHxZWJN5onv0fVZj6iceBwHSo/5pprgwPEFFhX1r9sqlux1fCv9oD+L7I7WTAZmMbBXEFvnwCc/8ds7xWzZ6TTsUrCxkbfZBKpeZl1+xWvPZK9bRicO4PA180KfZyGZkxnFZG9JuvYO8nyC3eaafO4U3nDuoDNSqvl3Lbs3d9BSJC1fP6fPvyIuHdexrr42WIo/tM=
  template:
    metadata:
      creationTimestamp: null
      name: website-db-credentials
      namespace: portfolio
